// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeqnioV2DkqVXxJX6IVN9r6LnfN_2HDHs',
    appId: '1:97746580683:web:e442427abb5eb4acd6174e',
    messagingSenderId: '97746580683',
    projectId: 'gvghvgh-e5ced',
    authDomain: 'gvghvgh-e5ced.firebaseapp.com',
    storageBucket: 'gvghvgh-e5ced.appspot.com',
    measurementId: 'G-46JKYG5CF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6b-vt5Kkd6eH68E7a78TCa42XYmbGNro',
    appId: '1:97746580683:android:1dd24e928f5499f7d6174e',
    messagingSenderId: '97746580683',
    projectId: 'gvghvgh-e5ced',
    storageBucket: 'gvghvgh-e5ced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7CXEaSVb0SZfslZczZPEwECp9dBRpxNA',
    appId: '1:97746580683:ios:cda952ae9d5eb5c8d6174e',
    messagingSenderId: '97746580683',
    projectId: 'gvghvgh-e5ced',
    storageBucket: 'gvghvgh-e5ced.appspot.com',
    iosBundleId: 'com.example.solutionChallengeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7CXEaSVb0SZfslZczZPEwECp9dBRpxNA',
    appId: '1:97746580683:ios:d94cb123eb85f36fd6174e',
    messagingSenderId: '97746580683',
    projectId: 'gvghvgh-e5ced',
    storageBucket: 'gvghvgh-e5ced.appspot.com',
    iosBundleId: 'com.example.solutionChallengeApp.RunnerTests',
  );
}
